
fos_rest:
    body_listener: true
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
            xml: false
            rss: false
        mime_types:
            json: ['application/json', 'application/x-json']
            jpg: ['image/jpeg']
            png: ['image/png']
    routing_loader:
        default_format:  json
        include_format:  false
    format_listener:
        enabled: true
        rules:
            - {
                path: ^/,
                priorities: [ json ],
                fallback_format: json,
                prefer_extension: true
                }
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
